Fix typos
ttu/kotlin-is-like-csharp pull request #17
Opened 2024-08-16 22:16 UTC by megabyte6

Mainly fixes typos and the misuse of `<` in HTML by replacing them with `&lt;`.

Requested in #13

2024-08-22 19:01 UTC, ttu requested changes
Hi and thanks again for finding time to make improvements.

index.html is generated from index.cirru and code-files defined in there.
https://github.com/ttu/kotlin-is-like-csharp/blob/1326faf5a49283dcfb9ea7c99a3120d236945e52/index.cirru

e.g.
```
for (i in 0..&lt;count) {
    println("Person ${i + 1} is called ${names[i]}")
}
````
can be found from https://github.com/ttu/kotlin-is-like-csharp/blob/1326faf5a49283dcfb9ea7c99a3120d236945e52/code/range-operator.kt

Would you like to make changes to code files and regenerate the index.html?
On README there is a guide how to regenerate the file.
https://github.com/ttu/kotlin-is-like-csharp?tab=readme-ov-file#develop

2024-12-20 07:12 UTC, megabyte6 commented
@ttu apologies for the incredibly long delay. I got quite busy with school along with other personal events.

I figured it might be good to replace `<` with `&lt;` in the build process instead of replacing the source code to keep the Kotlin and C# code pure.

I was looking into the use of the `mission` package and wanted to know if you'd be open to removing its reliance since that project has been archived for many years. In addition, when running `npm i`, I get many deprecation warnings from `mission` on top of the many installation errors. I don't believe that continuing to rely on `mission` would be good for the project's maintainability.

We would need to reimplement many of its features to remove `mission`. If you give me the go-ahead, I'm happy to attempt this.

On another note, I am quite unfamiliar with CoffeeScript. From the looks of it, you were using it for `mission` support. Since we are removing `mission,` what do you think about rewriting `make.coffee` in TypeScript or JavaScript (most likely the latter)? If I'm wrong about the intention, please let me know.

Overall, I'm not too worried about CoffeeScript, but I am mainly concerned about the use of `mission`.

2025-01-13 20:48 UTC, ttu commented
@megabyte6 Thanks for the interest.

This project was based on the other `xxx-is-like-yyy` projects and all of those used `cirru` templates and generated the html with `coffeescript` & `mission`. If you have interest you could check how to replace mission's cirru to html functionality. Not sure how easy it is to find some cirru to html library as all might be deprecated, e.g. https://github.com/Cirru/cirru-html 😄 Of course on option is to convert cirru template to some other template language, but that might be a bigger task.

Just let me know if you have some questions and feel like trying to modernize the tools used in this project.

2025-01-16 19:02 UTC, megabyte6 commented
@ttu Oh I see. In that case, I agree with you. There would have to be huge changes, possibly across multiple projects. I'll just make the changes you recommended, namely adding `&lt` to the Kotlin and C# files directly, and update this pull request.

2025-01-16 19:16 UTC, megabyte6 commented
@ttu Alright, this pull request has been updated with the fixes you recommended.

2026-02-15 06:03 UTC, ttu approved these changes

2026-02-15 06:05 UTC, ttu commented
Sorry! I completely missed the last update notification. Thanks for reminding me!

2026-02-15 06:07 UTC, merged